package core

// ChunkMeta contains fixed metadata for a chunk related to its position and hierarchy.
type ChunkMeta struct {
	Index        int      `json:"index"`         // 分块在文档中的序号（0,1,2...）
	StartPos     int      `json:"start_pos"`     // 分块在原始清洗后文本中的起始位置
	EndPos       int      `json:"end_pos"`       // 分块在原始清洗后文本中的结束位置
	HeadingLevel int      `json:"heading_level"` // 分块对应的标题层级（来自 StructureNode）
	HeadingPath  []string `json:"heading_path"`  // 分块对应的标题路径（如 ["第一章","1.1节"]）
}

// Chunk represents an indexable unit generated by a Chunker.
// It carries all information from the parsing layer including content, metadata,
// and positional information for retrieval.
type Chunk struct {
	ID        string         `json:"id"`         // Chunk 唯一ID
	ParentID  string         `json:"parent_id"`  // 父Chunk/父文档ID（来自 RawDocument.Source）
	DocID     string         `json:"doc_id"`     // 原始文档ID（来自 RawDocument.ID）
	Title     string         `json:"title"`      // Chunk 标题（LLM 生成或从 heading 提取）
	MIMEType  string         `json:"mime_type"`  // 内容类型
	Content   string         `json:"content"`    // 分块内容（清洗后纯文本）
	Metadata  map[string]any `json:"metadata"`   // 扩展元数据（来自 RawDocument.Metadata）
	ChunkMeta ChunkMeta      `json:"chunk_meta"` // 分块固定元数据
}
