// Package core provides fundamental types and interfaces for the goRAG framework.
// It defines the building blocks for document processing, chunking, embedding,
// indexing, and retrieval in a RAG (Retrieval-Augmented Generation) system.
package core

import (
	"github.com/DotNetAge/gorag/v2/utils"
)

// StructureNode represents a structural unit within a parsed document.
// It corresponds to headings, paragraphs, lists, tables, and other document elements.
// StructureNodes form a tree hierarchy that preserves the document's logical structure.
type StructureNode struct {
	NodeType string           `json:"node_type"` // 节点类型（heading/paragraph/table/list 等）
	Title    string           `json:"title"`     // 节点标题（仅 heading 类型有效）
	Level    int              `json:"level"`     // 标题层级（仅 heading 类型有效，H1=1、H2=2...）
	Text     string           `json:"text"`      // 清洗后的纯文本内容（核心，无任何格式垃圾）
	StartPos int              `json:"start_pos"` // 文本在原始清洗后内容中的起始位置（用于分块定位）
	EndPos   int              `json:"end_pos"`   // 文本在原始清洗后内容中的结束位置（用于分块定位）
	Children []*StructureNode `json:"children"`  // 子节点（如 H1 下的 H2、段落下的列表）
}

// ID generates a unique identifier for this node based on its text content.
// Returns empty string if the node has no text.
func (n *StructureNode) ID() string {
	if n.Text == "" {
		return ""
	}
	return utils.GenerateID([]byte(n.Text))
}

// Clean cleans the Text and Title fields of this node and recursively cleans all child nodes.
// Cleaning includes removing noise, normalizing text, and applying privacy filters.
func (n *StructureNode) Clean() {
	// 清洗 Title 字段（仅对 heading 类型有效）
	if n.NodeType == "heading" && n.Title != "" {
		n.Title = CleanText(n.Title)
	}

	// 清洗 Text 字段
	if n.Text != "" {
		n.Text = CleanText(n.Text)
	}

	// 递归清洗子节点
	for _, child := range n.Children {
		child.Clean()
	}
}

// CleanText applies all cleaning functions in the default order to sanitize text.
// The cleaning pipeline processes text through these stages:
//  1. Full-width/half-width character conversion
//  2. Noise character removal (control characters, excess whitespace)
//  3. Link removal (Markdown, HTML, bare URLs)
//  4. Code line number removal
//  5. Watermark removal
//  6. Chinese character normalization (traditional → simplified)
//  7. PII desensitization (ID numbers, phones, bank cards, API keys, emails)
//  8. Paragraph normalization (merge excess newlines, trim whitespace)
//  9. Basic cleaning (special characters, merge spaces)
func CleanText(text string) string {
	if text == "" {
		return ""
	}

	// 1. 全角半角转换（先处理字符编码问题）
	text = utils.ToHalfWidth(text)

	// 2. 去除噪音字符（控制字符、多余空白等）
	text = utils.CleanNoise(text)

	// 3. 去除链接（Markdown链接、HTML链接、裸露URL）
	text = utils.RemoveLinks(text)

	// 4. 去除代码行号
	text = utils.RemoveLineNumbers(text)

	// 5. 去除水印
	text = utils.RemoveWatermarks(text)

	// 6. 繁简转换（统一为简体中文）
	text = utils.NormalizeChinese(text)

	// 7. 隐私脱敏（身份证、手机号、银行卡、API密钥、邮箱）
	text = utils.DesensitizePII(text)

	// 8. 段落规范化（合并多余换行、去除行首行尾空格）
	text = utils.NormalizeParagraphs(text)

	// 9. 去除停用词（可选，根据场景决定是否启用）
	// text = utils.RemoveStopWords(text)

	// 10. 基础清洗（去特殊字符、合并空格）
	text = utils.Clean(text)

	return text
}

// StructuredDocument represents a document with its hierarchical structure preserved.
// It wraps the raw document and provides access to the parsed structure tree.
type StructuredDocument struct {
	RawDoc Document       `json:"raw_doc"` // 原始文档对象
	Title  string         `json:"title"`   // 文档总标题（清洗后）
	Root   *StructureNode `json:"root"`    // 文档结构根节点（顶层节点）
}

// ID returns the unique identifier of the original document.
func (s *StructuredDocument) ID() string {
	return s.RawDoc.GetID()
}

// Meta returns the metadata map from the underlying raw document.
func (s *StructuredDocument) Meta() map[string]any {
	return s.RawDoc.GetMeta()
}

// SetValue sets a key-value pair in the document's metadata and returns the document for chaining.
func (s *StructuredDocument) SetValue(key string, value any) *StructuredDocument {
	s.RawDoc.GetMeta()[key] = value
	return s
}


// ChunkMeta contains fixed metadata for a chunk related to its position and hierarchy.
type ChunkMeta struct {
	Index        int      `json:"index"`         // 分块在文档中的序号（0,1,2...）
	StartPos     int      `json:"start_pos"`     // 分块在原始清洗后文本中的起始位置
	EndPos       int      `json:"end_pos"`       // 分块在原始清洗后文本中的结束位置
	HeadingLevel int      `json:"heading_level"` // 分块对应的标题层级（来自 StructureNode）
	HeadingPath  []string `json:"heading_path"`  // 分块对应的标题路径（如 ["第一章","1.1节"]）
}

// Chunk represents an indexable unit generated by a Chunker.
// It carries all information from the parsing layer including content, metadata,
// and positional information for retrieval.
type Chunk struct {
	ID        string         `json:"id"`         // Chunk 唯一ID
	ParentID  string         `json:"parent_id"`  // 父Chunk/父文档ID（来自 RawDocument.Source）
	DocID     string         `json:"doc_id"`     // 原始文档ID（来自 RawDocument.ID）
	Title     string         `json:"title"`      // Chunk 标题（LLM 生成或从 heading 提取）
	MIMEType  string         `json:"mime_type"`  // 内容类型
	Content   string         `json:"content"`    // 分块内容（清洗后纯文本）
	Metadata  map[string]any `json:"metadata"`   // 扩展元数据（来自 RawDocument.Metadata）
	ChunkMeta ChunkMeta      `json:"chunk_meta"` // 分块固定元数据
}

// Hit represents a search result with relevance scoring and content.
// GraphIndexer 的 Hits 同时包含 Chunk + Entities + Relations，客户端可直接使用。
type Hit struct {
	ID        string         `json:"id"`          // 结果ID
	Title     string         `json:"title"`       // 结果标题（来自原 Chunk.Title）
	Score     float32        `json:"score"`       // 相似度分数
	Content   string         `json:"content"`     // 结果内容
	DocID     string         `json:"doc_id"`      // 文档ID
	Metadata  map[string]any `json:"metadata"`    // 扩展元数据（来自原 Chunk.Metadata）
	ChunkMeta ChunkMeta      `json:"chunk_meta"`  // 分块固定元数据（来自原 Chunk.ChunkMeta）
	Entities  []*Node        `json:"entities,omitempty"`   // 关联的实体节点（GraphIndexer 专用）
	Relations []*Edge        `json:"relations,omitempty"`  // 关联的边（GraphIndexer 专用）
}
