// Package core defines the fundamental entities, interfaces, and types for the goRAG framework.
package core

import (
	"context"

	chat "github.com/DotNetAge/gochat/pkg/core"
)

// AgentStep tracks intermediate thoughts, tool calls, and observations for ReAct/Agentic RAG.
// Each step represents one iteration in the reasoning-action-observation cycle.
//
// Fields:
//   - Thought: The agent's reasoning about what to do next
//   - Action: The name of the tool or action to execute
//   - ActionInput: The input parameters for the action
//   - Observation: The result or output from executing the action
type AgentStep struct {
	Thought     string
	Action      string
	ActionInput ToolInput
	Observation string
}

// AgentResponse is the final multi-hop output from an Agent.
// It contains the final answer and the complete reasoning chain.
//
// Fields:
//   - Response: The final answer generated by the agent
//   - Steps: The complete sequence of reasoning steps taken
type AgentResponse struct {
	Response string
	Steps    []AgentStep
}

// Agent defines the core interface for agentic RAG implementations.
// It mimics LangChain's AgentExecutor and LlamaIndex AgentRunner patterns,
// enabling dynamic planning and multi-step reasoning for complex queries.
//
// Agents use a ReAct (Reasoning + Acting) loop to:
//  1. Analyze the query and determine the next action
//  2. Execute tools to gather information
//  3. Reason about the results
//  4. Repeat until a final answer can be provided
//
// Example usage:
//
//	agent := NewMyAgent(llm, tools)
//	response, err := agent.Chat(ctx, "What is the revenue of Company X?", history)
//	if err != nil {
//	    log.Fatal(err)
//	}
//	fmt.Println(response.Response)
type Agent interface {
	// Name returns the agent's identifier or persona name.
	// This is used for logging, routing, and debugging purposes.
	Name() string

	// AddTool registers a new tool that the agent can use during reasoning.
	// Tools extend the agent's capabilities for tasks like search, calculation, or API calls.
	//
	// Parameters:
	//   - tool: The tool implementation to add
	AddTool(tool Tool)

	// Chat executes the ReAct loop to answer a query.
	// It dynamically plans and resolves tools until reaching a final answer.
	//
	// Parameters:
	//   - ctx: Context for cancellation and timeout
	//   - query: The user's question or request
	//   - history: Previous conversation messages for context
	//
	// Returns:
	//   - *AgentResponse: The final answer and reasoning steps
	//   - error: Any error that occurred during execution
	Chat(ctx context.Context, query string, history []chat.Message) (*AgentResponse, error)

	// Memory returns the agent's conversation memory store.
	// This enables multi-turn conversations with context retention.
	Memory() ChatMemory
}
